# name = "domain-check"
main = "src/index.js"
compatibility_date = "2025-11-17"
keep_vars = true

# KV 命名空间绑定 (必须)
[[kv_namespaces]]
binding = "domain_check_101001" 
id = "43039829ddf944b9a4a68c9a6135e941" # 替换成你实际的 KV ID

# Cron Triggers 定时任务
[triggers]
crons = ["0 1,13 * * *"] # 北京时间 9:00 和 21:00
